import Sidebar from "@/app/components/sidebar";
import "./globals.css";
import { personalData } from "./data/page-data";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col sm:flex-row">
        <Sidebar data={personalData} />
        <main className="grow-full w-full p-8 sm:p-16 sm:basis-2/3  ml-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
